project:
  type: website

website:
  title: "The busy triathlete"
  site-url: https://theasjblog.github.io/sport_blog/
  description: "The busy triatlhete blog"
  cookie-consent: true
  google-analytics: "G-53CD66TT4Z"
  navbar:
    right:
      - icon: strava
        href: https://www.strava.com/athletes/7974168
      - text: "{{< iconify cib:garmin >}}"
        href: https://connect.garmin.com/modern/profile/adrianstevejoseph
      - icon: rss
        href: index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
