project:
  type: website

website:
  title: "Sport Blog"
  navbar:
    right:
      - about.qmd
      - icon: strava
        href: https://www.strava.com/athletes/7974168

format:
  html:
    theme: cosmo
    css: styles.css



